# VARIABLE SCOPE - Where a variable is visible and accessible
# SCOPE RESOLUTION - (LEGB) Local -> Enclose -> Global -> Built-in

x = 3                      # GLOBAL VARIABLE
def func1():
    a = 1                  # LOCAL VARIABLE
    print(a)
  # print(b) #ERROR
def func2():
    b = 2                  # LOCAL VARIABLE
    print(b)
  # print(a) #ERROR

func1()
func2()


# CONCLUSION - YUNG DINECLARE NATING VARIABLE INSIDE SA ISANG FUNCTION E DI NATIN MA CACALL SA ISA PANG FUNCTION
# YUNG GLOBAL VARIABLE PWEDE NATING I CALL SA BAWAT ISANG FUNCTION
# PAG NAMAN MAGKAPAREHO YUNG NAME NG BUILT IN NA INIMPORT NATIN (From math import e : exponential value) sa VARIABLE -
# NA DINECLARE NATIN AS GLOBAL VARIABLE, YUNG GLOBAL VARIABLE YUNG MAKUKUHA, IF MAY LOCAL VARIABLE NA KAPAREHO NILA  -
# EH LOCAL VARIABLE YUNG MAKUKUHA SA FUNCTION. LOCAL > GLOBAL > BUILT IN

# ENCLOSE
def name():
    first_name = "Rency"

    def last_name():
      # first_name = "Pate"
        print(f"{first_name}")
    last_name()

name()

# CONCLUSION - KAPAG NAMAN MAY FUNCTION SA LOOB NG ISA PANG FUNCTION
# IF WALANG LOCAL VARIABLE PAG TINAWAG YUNG FUNCTION NA NASA LOOB (KUNG MAY KAPAREHONG VARIABLE ITO SAKA SA NASA LABAS)
# KUKUNIN NG FUNCTION NA NASA LOOB YUNG VARIABLE NG NASA LABAS NA FUNCTION.
# PERO DAPAT NA CALL DIN YUNG FUNCTION NA NASA LABAS KAHIT DI PINRINT YUNG VARIABLE NA NANDOON.

